import type { OneRouter } from 'one'

declare module 'one' {
  export namespace OneRouter {
    export interface __routes<T extends string = string> extends Record<string, unknown> {
      StaticRoutes: `/` | `/(home)` | `/(home)/` | `/(tabs)` | `/(tabs)/` | `/(tabs)/(home)` | `/(tabs)/(home)/` | `/(tabs)/communities` | `/(tabs)/communities/` | `/(tabs)/create` | `/(tabs)/inbox` | `/(tabs)/inbox/` | `/(tabs)/settings` | `/_sitemap` | `/auth` | `/communities` | `/communities/` | `/create` | `/inbox` | `/inbox/` | `/md` | `/settings`
      DynamicRoutes: `/(home)/c/${OneRouter.SingleRoutePart<T>}` | `/(home)/c/${OneRouter.SingleRoutePart<T>}/posts/${OneRouter.SingleRoutePart<T>}` | `/(home)/c/${OneRouter.SingleRoutePart<T>}/posts/${OneRouter.SingleRoutePart<T>}/comments/${OneRouter.SingleRoutePart<T>}` | `/(home)/c/${OneRouter.SingleRoutePart<T>}/s/${OneRouter.SingleRoutePart<T>}` | `/(home)/s/${OneRouter.SingleRoutePart<T>}` | `/(tabs)/(home)/c/${OneRouter.SingleRoutePart<T>}` | `/(tabs)/(home)/c/${OneRouter.SingleRoutePart<T>}/posts/${OneRouter.SingleRoutePart<T>}` | `/(tabs)/(home)/c/${OneRouter.SingleRoutePart<T>}/posts/${OneRouter.SingleRoutePart<T>}/comments/${OneRouter.SingleRoutePart<T>}` | `/(tabs)/(home)/c/${OneRouter.SingleRoutePart<T>}/s/${OneRouter.SingleRoutePart<T>}` | `/(tabs)/(home)/s/${OneRouter.SingleRoutePart<T>}` | `/(tabs)/c/${OneRouter.SingleRoutePart<T>}` | `/(tabs)/c/${OneRouter.SingleRoutePart<T>}/posts/${OneRouter.SingleRoutePart<T>}` | `/(tabs)/c/${OneRouter.SingleRoutePart<T>}/posts/${OneRouter.SingleRoutePart<T>}/comments/${OneRouter.SingleRoutePart<T>}` | `/(tabs)/c/${OneRouter.SingleRoutePart<T>}/s/${OneRouter.SingleRoutePart<T>}` | `/(tabs)/communities/c/${OneRouter.SingleRoutePart<T>}` | `/(tabs)/communities/c/${OneRouter.SingleRoutePart<T>}/posts/${OneRouter.SingleRoutePart<T>}` | `/(tabs)/communities/c/${OneRouter.SingleRoutePart<T>}/posts/${OneRouter.SingleRoutePart<T>}/comments/${OneRouter.SingleRoutePart<T>}` | `/(tabs)/communities/c/${OneRouter.SingleRoutePart<T>}/s/${OneRouter.SingleRoutePart<T>}` | `/(tabs)/inbox/c/${OneRouter.SingleRoutePart<T>}` | `/(tabs)/inbox/c/${OneRouter.SingleRoutePart<T>}/posts/${OneRouter.SingleRoutePart<T>}` | `/(tabs)/inbox/c/${OneRouter.SingleRoutePart<T>}/posts/${OneRouter.SingleRoutePart<T>}/comments/${OneRouter.SingleRoutePart<T>}` | `/(tabs)/inbox/c/${OneRouter.SingleRoutePart<T>}/s/${OneRouter.SingleRoutePart<T>}` | `/(tabs)/s/${OneRouter.SingleRoutePart<T>}` | `/c/${OneRouter.SingleRoutePart<T>}` | `/c/${OneRouter.SingleRoutePart<T>}/posts/${OneRouter.SingleRoutePart<T>}` | `/c/${OneRouter.SingleRoutePart<T>}/posts/${OneRouter.SingleRoutePart<T>}/comments/${OneRouter.SingleRoutePart<T>}` | `/c/${OneRouter.SingleRoutePart<T>}/s/${OneRouter.SingleRoutePart<T>}` | `/communities/c/${OneRouter.SingleRoutePart<T>}` | `/communities/c/${OneRouter.SingleRoutePart<T>}/posts/${OneRouter.SingleRoutePart<T>}` | `/communities/c/${OneRouter.SingleRoutePart<T>}/posts/${OneRouter.SingleRoutePart<T>}/comments/${OneRouter.SingleRoutePart<T>}` | `/communities/c/${OneRouter.SingleRoutePart<T>}/s/${OneRouter.SingleRoutePart<T>}` | `/inbox/c/${OneRouter.SingleRoutePart<T>}` | `/inbox/c/${OneRouter.SingleRoutePart<T>}/posts/${OneRouter.SingleRoutePart<T>}` | `/inbox/c/${OneRouter.SingleRoutePart<T>}/posts/${OneRouter.SingleRoutePart<T>}/comments/${OneRouter.SingleRoutePart<T>}` | `/inbox/c/${OneRouter.SingleRoutePart<T>}/s/${OneRouter.SingleRoutePart<T>}` | `/s/${OneRouter.SingleRoutePart<T>}`
      DynamicRouteTemplate: `/(home)/c/[communityName]` | `/(home)/c/[communityName]/posts/[postId]` | `/(home)/c/[communityName]/posts/[postId]/comments/[commentPath]` | `/(home)/c/[communityName]/s/[search]` | `/(home)/s/[search]` | `/(tabs)/(home)/c/[communityName]` | `/(tabs)/(home)/c/[communityName]/posts/[postId]` | `/(tabs)/(home)/c/[communityName]/posts/[postId]/comments/[commentPath]` | `/(tabs)/(home)/c/[communityName]/s/[search]` | `/(tabs)/(home)/s/[search]` | `/(tabs)/c/[communityName]` | `/(tabs)/c/[communityName]/posts/[postId]` | `/(tabs)/c/[communityName]/posts/[postId]/comments/[commentPath]` | `/(tabs)/c/[communityName]/s/[search]` | `/(tabs)/communities/c/[communityName]` | `/(tabs)/communities/c/[communityName]/posts/[postId]` | `/(tabs)/communities/c/[communityName]/posts/[postId]/comments/[commentPath]` | `/(tabs)/communities/c/[communityName]/s/[search]` | `/(tabs)/inbox/c/[communityName]` | `/(tabs)/inbox/c/[communityName]/posts/[postId]` | `/(tabs)/inbox/c/[communityName]/posts/[postId]/comments/[commentPath]` | `/(tabs)/inbox/c/[communityName]/s/[search]` | `/(tabs)/s/[search]` | `/c/[communityName]` | `/c/[communityName]/posts/[postId]` | `/c/[communityName]/posts/[postId]/comments/[commentPath]` | `/c/[communityName]/s/[search]` | `/communities/c/[communityName]` | `/communities/c/[communityName]/posts/[postId]` | `/communities/c/[communityName]/posts/[postId]/comments/[commentPath]` | `/communities/c/[communityName]/s/[search]` | `/inbox/c/[communityName]` | `/inbox/c/[communityName]/posts/[postId]` | `/inbox/c/[communityName]/posts/[postId]/comments/[commentPath]` | `/inbox/c/[communityName]/s/[search]` | `/s/[search]`
      IsTyped: true
    }
  }
}